### PR TITLE
Make typings compatible w/ react-native@0.34

### PR DESCRIPTION
**Pull request by vladimir-kotikov**

### CODE REVIEW

**Comment by MSLaguana** [comment]
Hmm, the CI failed the build, but it seems unrelated to the contents of the PR. Might be to do with updates to vscode itself perhaps?

**Comment by vladimir-kotikov** [comment]
@MSLaguana, it appeared that vscode test app was the culprit. Adding it to  excludes did the trick.

**Comment by forki** [comment]
(so VSCode is currently not compatible with v34?)

**Comment by vladimir-kotikov** [comment]
@forki, not that it is not compatible - I'd say it's not up to date with current react-native. Current typings were written to match react-native@0.29, so they might be a bit outdated if you're using 0.34.

Also, some of APIs were not covered by typings, and this PR fixes this problem too.

**Comment by mbraude** [comment]
@MSLaguana can you help get this PR checked in?

**Pull request merged**
