### PR TITLE
Updated .gitignore to reflect SampleApplication new path

### PR DESCRIPTION
**Pull request by digeff**
Updated .gitignore to reflect SampleApplication new path

### CODE REVIEW

**Comment by dlebu** [comment]
The change looks good. Can you rename the top folder from `SampleApplication` to `sample-application` to match the other folders?

**Comment by digeff** [comment]
We have stuff with different conventions: ReactTypings, SampleApplication, js-patched, react-native and files in camel case.
If the whole team agrees with a convention we should follow, I'm happy to make the change.

**Comment by dlebu** [comment]
I think that in order to have consistent naming and minimal changes we should:

- keep files in camel case
- change folder names to lower case and use `-` as a separator

**Comment by digeff** [comment]
I'll merge this PR. If the team decides to go with:
keep files in camel case
change folder names to lower case and use - as a separator
I'll create a new PR with that change.

**Pull request merged**
