### PR TITLE
Fix for incorrect builder restarts

### PR DESCRIPTION
**Pull request by iTOYS**
Support for VSCode@1.14.0
#471

### CODE REVIEW

**Comment by Jkaveri** [comment]
This fix works on my end. Thank you very much.

**Comment by iainroyle** [comment]
How can I install the latest update? Let me know and I'll test. Thanks.

**Comment by Jkaveri** [comment]
@iainroyle I updated the file `~\.vscode\extensions\vsmobile.vscode-react-native-0.3.2\out\debugger\nodeDebugWrapper.js` :)

Thank you

**Comment by vladimir-kotikov** [comment]
@iainroyle another option is to clone this repo, build it (`gulp build`) and then create a symlink to it at `~\.vscode\extensions`

**Comment by christ776** [comment]
Hi, 

I'm trying to build it locally, just installed gulp globally, then installed gulp locally on the project dir and I'm now getting this

```christian@Christians-MacBook-Pro:~/Documents/JavaScript/vscode-react-native$ gulp build
module.js:471
    throw err;
    ^

Error: Cannot find module 'gulp-sourcemaps'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/christian/Documents/JavaScript/vscode-react-native/gulpfile.js:6:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by iTOYS** [comment]
Hi @christ776
Did you run `npm install` in extension folder before?

**Comment by christ776** [comment]
Oh, that did the trick. Sorry !
```
[12:25:43] Using gulpfile ~/Documents/JavaScript/vscode-react-native/gulpfile.js
[12:25:43] Starting 'check-imports'...
[12:25:43] Starting 'check-copyright'...
[12:25:47] Finished 'check-copyright' after 3.7 s
[12:25:47] Finished 'check-imports' after 3.83 s
[12:25:47] Starting 'build'...
[12:25:47] Building with preprocessor context: {"PROD":true}
[12:25:49] Finished 'build' after 2.55 s
```

**Comment by iainroyle** [comment]
Thanks for your help. Works for me now.

**Comment by nomikeeper** [comment]
How can I do those steps on Mac, I tried to find nodeDebugWrapper.js but due to VSCode stable edition (portable I guess) I couldn't find it. About installing gulp I can't find the extension folder. Where can I find it?

**Pull request merged**
