### PR TITLE
fix typo and remove console.log (overriden -> overridden)

### PR DESCRIPTION
**Pull request by mroswald**
fixes a typo and remove a console.log from production code

### CODE REVIEW

**Comment by digeff** [comment]
Thanks for fixing this! :+1:

**Comment by MSLaguana** [comment]
Looks good to me. Once you sign the CLA we can merge the PR.

**Comment by mroswald** [comment]
@MSLaguana don't know how long this will take, uploaded the signed CLA an hour ago

**Comment by MSLaguana** [comment]
No problem, I'll merge this in once the form is approved.

**Pull request merged**
