### PR TITLE
Updating package.json to include marketplace-parsable bugs/license fields

### PR DESCRIPTION
**Pull request by MSLaguana**

### CODE REVIEW

**Comment by meenakb** [comment]
While you are at it, please remove the "private" flag as well.

**Comment by MSLaguana** [comment]
I'm inclined to keep it there: vsce does not care about the "private" flag, and this will help ensure that we don't accidentally publish to NPM, since this is not actually a npm package.

**Comment by meenakb** [comment]
Good point, in that case please add it to vscode-cordova as well

**Comment by meenakb** [comment]
:+1:

**Comment by digeff** [comment]
:+1:

**Pull request merged**
