### PR TITLE
Allow to set breakpoints in original source files

### LINKED ISSUE #328: Can't add breakpoint, source maps issue?
## Actual Behavior
1. I run the Debug iOS command from the debugger panel 
2. Everything appears to load correctly into the Simulator and I'm able to compile my ts properly resulting in changes in the Simulator
3. I click to add a breakpoint to index.ios.tsx
4. Breakpoint appears grayed out and when I hover I see this message:
   "Breakpoint ignored because generated source code not found (source map problem?)"
   sharing_frame_window
## Expected Behavior
1. I run the Debug iOS command from the debugger panel 
2. Everything appears to load correctly into the Simulator and I'm able to compile my ts properly resulting in changes in the Simulator
3. I click to add a breakpoint to index.ios.tsx
4. Breakpoint is added and I'm able to refresh the simulator and see it catch
## Software versions
- React-Native VS Code extension version: 0.2.1
- VSCode version: 1.6.1
- OS platform and version: Mac OS Sierra v10.12.1
- React Native version: 0.32.1
## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console): 
  [vscode-react-native] Starting React Native Packager.
  [vscode-react-native] Prewarming bundle cache. This may take a while ...
  [vscode-react-native] Building and running application.
  [vscode-react-native] Executing command: react-native run-ios --simulator iPhone 5s --project-path ios
  Found Xcode project TypescriptTest3.xcodeproj
  Launching iPhone 5s (10.0)...
  Building using "xcodebuild -project TypescriptTest3.xcodeproj -scheme TypescriptTest3 -destination id=E3F427C1-5B10-45B9-AE0E-313C6E72965F -derivedDataPath build"
  User defaults from command line:
  IDEDerivedDataPathOverride = /Users/davidhelmer/Work/React Native/TypescriptTest4/ios/build
  === BUILD TARGET RCTVibration OF PROJECT RCTVibration WITH CONFIGURATION Debug ===
  Check dependencies
  === BUILD TARGET RCTGeolocation OF PROJECT RCTGeolocation WITH CONFIGURATION Debug ===
  Check dependencies
  === BUILD TARGET RCTLinking OF PROJECT RCTLinking WITH CONFIGURATION Debug ===
  Check dependencies
  === BUILD TARGET React OF PROJECT React WITH CONFIGURATION Debug ===
  Check dependencies
  PhaseScriptExecution Run\ Script /Users/davidhelmer/Work/React\ Native/TypescriptTest4/ios/build/Build/Intermediates/React.build/Debug-iphonesimulator/React.build/Script-006B79A01A781F38006873D1.sh
  cd "/Users/davidhelmer/Work/React Native/TypescriptTest4/node_modules/react-native/React"
  export ACTION=build
  export AD_HOC_CODE_SIGNING_ALLOWED=NO
  export ALTERNATE_GROUP=staff
  export ALTERNATE_MODE=u+w,go-w,a+rX
  export ALTERNATE_OWNER=davidhelmer
  export ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=NO
  export ALWAYS_SEARCH_USER_PATHS=NO
  export ALWAYS_USE_SEPARATE_HEADERMAPS=NO
  export APPLE_INTERNAL_DEVELOPER_DIR=/AppleInternal/Developer
  export APPLE_INTERNAL_DIR=/AppleInternal
  export APPLE_INTERNAL_DOCUMENTATION_DIR=/AppleInternal/Documentation
  export APPLE_INTERNAL_LIBRARY_DIR=/AppleInternal/Library
  export APPLE_INTERNAL_TOOLS=/AppleInternal/Developer/Tools
  export APPLICATION_EXTENSION_API_ONLY=NO
  export APPLY_RULES_IN_COPY_FILES=NO
  export ARCHS=x86_64
  export ARCHS_STANDARD="i386 x86_64"
  export ARCHS_STANDARD_32_64_BIT="i386 x86_64"
  export ARCHS_STANDARD_32_BIT=i386
  export ARCHS_STANDARD_64_BIT=x86_64
  export ARCHS_STANDARD_INCLUDING_64_BIT="i386 x86_64"
  export ARCHS_UNIVERSAL_IPHONE_OS="i386 x86_64"
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox): 
  Getting exponent dependecy.
  Dependency not present. Installing it...
  ######### Checking react native is correctly setup. This may take a while... ##########
  Checking if the correct react native is installed..
  ######### Starting Packager ##########
  ######### Executing command: react-native start --port 8081 ##########
  ..Scanning 647 folders for symlinks in /Users/davidhelmer/Work/React Native/TypescriptTest4/node_modules (21ms)
  ┌────────────────────────────────────────────────────────────────────────────┐ 
  │  Running packager on port 8081.                                            │ 
  │                                                                            │ 
  │  Keep this packager running while developing on any JS projects. Feel      │ 
  │  free to close this tab and run your own packager instance if you          │ 
  │  prefer.                                                                   │ 
  │                                                                            │ 
  │  https://github.com/facebook/react-native                                  │ 
  │                                                                            │ 
  └────────────────────────────────────────────────────────────────────────────┘ 
  Looking for JS files in
  /Users/davidhelmer/Work/React Native/TypescriptTest4 

.[11:35:12 AM] <START> Building Dependency Graph
[11:35:12 AM] <START> Crawling File System
[Hot Module Replacement] Server listening on /hot

React packager ready.

[11:35:12 AM] <END>   Crawling File System (443ms)
[11:35:12 AM] <START> Building in-memory fs for JavaScript
[11:35:13 AM] <END>   Building in-memory fs for JavaScript (508ms)
[11:35:13 AM] <START> Building in-memory fs for Assets
[11:35:13 AM] <END>   Building in-memory fs for Assets (413ms)
[11:35:13 AM] <START> Building Haste Map
.[11:35:13 AM] <START> Building (deprecated) Asset Map
[11:35:14 AM] <END>   Building (deprecated) Asset Map (167ms)
[11:35:14 AM] <END>   Building Haste Map (458ms)
[11:35:14 AM] <END>   Building Dependency Graph (1874ms)
###### ### Packager started.

[11:35:14 AM] <START> request:/index.ios.bundle?platform=ios
[11:35:14 AM] <START> find dependencies
...................[11:35:42 AM] <START> request:/build/index.ios.bundle?platform=ios&dev=true&minify=false
[11:35:42 AM] <START> find dependencies
Starting custom debugger by executing: echo A debugger is not needed:  "/Users/davidhelmer/Work/React Native/TypescriptTest4"
[11:35:43 AM] <START> request:/build/index.ios.bundle?platform=ios&dev=true&minify=false
.[11:35:44 AM] <END>   find dependencies (1970ms)
[11:35:44 AM] <END>   request:/build/index.ios.bundle?platform=ios&dev=true&minify=false (2184ms)
[11:35:44 AM] <END>   request:/build/index.ios.bundle?platform=ios&dev=true&minify=false (1068ms)
.........[11:36:04 AM] <START> request:/build/index.ios.bundle?platform=ios&dev=true&minify=false
[11:36:04 AM] <END>   request:/build/index.ios.bundle?platform=ios&dev=true&minify=false (24ms)
Starting custom debugger by executing: echo A debugger is not needed:  "/Users/davidhelmer/Work/React Native/TypescriptTest4"
......######### Stopping Packager ##########
###### ### Checking react native is correctly setup. This may take a while...

Checking if the correct react native is installed..
###### ### Executing command: react-native start --port 8081

Scanning 647 folders for symlinks in /Users/davidhelmer/Work/React Native/TypescriptTest4/node_modules (38ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/davidhelmer/Work/React Native/TypescriptTest4 

[11:44:40 AM] <START> Building Dependency Graph
[11:44:40 AM] <START> Crawling File System
[Hot Module Replacement] Server listening on /hot

React packager ready.

[11:44:40 AM] <END>   Crawling File System (284ms)
[11:44:40 AM] <START> Building in-memory fs for JavaScript
[11:44:40 AM] <END>   Building in-memory fs for JavaScript (251ms)
[11:44:40 AM] <START> Building in-memory fs for Assets
[11:44:41 AM] <END>   Building in-memory fs for Assets (201ms)
[11:44:41 AM] <START> Building Haste Map
[11:44:41 AM] <START> Building (deprecated) Asset Map
[11:44:41 AM] <END>   Building (deprecated) Asset Map (84ms)
###### ### Packager started.

[11:44:41 AM] <END>   Building Haste Map (278ms)
[11:44:41 AM] <END>   Building Dependency Graph (1024ms)
[11:44:41 AM] <START> request:/index.ios.bundle?platform=ios
[11:44:41 AM] <START> find dependencies
[11:44:59 AM] <START> request:/build/index.ios.bundle?platform=ios&dev=true&minify=false
[11:44:59 AM] <START> find dependencies
Starting custom debugger by executing: echo A debugger is not needed:  "/Users/davidhelmer/Work/React Native/TypescriptTest4"
[11:45:00 AM] <START> request:/build/index.ios.bundle?platform=ios&dev=true&minify=false
[11:45:00 AM] <END>   find dependencies (1796ms)
[11:45:00 AM] <END>   request:/build/index.ios.bundle?platform=ios&dev=true&minify=false (1926ms)
[11:45:00 AM] <END>   request:/build/index.ios.bundle?platform=ios&dev=true&minify=false (761ms)
[11:45:01 AM] <START> request:/build/index.ios.bundle?platform=ios&dev=true&minify=false
[11:45:01 AM] <END>   request:/build/index.ios.bundle?platform=ios&dev=true&minify=false (15ms)
[11:45:01 AM] <START> request:/build/index.ios.map?platform=ios&dev=true&minify=false
[11:45:01 AM] <END>   request:/build/index.ios.map?platform=ios&dev=true&minify=false (59ms)
[11:45:22 AM] <START> request:/build/index.ios.bundle?platform=ios&dev=true&minify=false
[11:45:22 AM] <END>   request:/build/index.ios.bundle?platform=ios&dev=true&minify=false (14ms)
Starting custom debugger by executing: echo A debugger is not needed:  "/Users/davidhelmer/Work/React Native/TypescriptTest4"
[11:45:22 AM] <START> request:/build/index.ios.bundle?platform=ios&dev=true&minify=false
[11:45:22 AM] <END>   request:/build/index.ios.bundle?platform=ios&dev=true&minify=false (11ms)
[11:45:22 AM] <START> request:/build/index.ios.map?platform=ios&dev=true&minify=false
[11:45:22 AM] <END>   request:/build/index.ios.map?platform=ios&dev=true&minify=false (57ms)
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):

### LINKED ISSUE #441: typescript breakpoints not working
## Actual Behavior
In debug breakpoints are not hit inside typescript files.

I have followed the suggestions from [#328](https://github.com/Microsoft/vscode-react-native/issues/328) and [#402](https://github.com/Microsoft/vscode-react-native/issues/402) without success. (I have downloaded the [ReactNativeTS](https://github.com/vladimir-kotikov/reactnativets) sample, I was able to hit the breakpoints only once...since then I have not been able to repeat my success...)

In tsconfig.json, I have these options:
```
"inlineSourceMap": true,
"sourceRoot": "/src"
```
In .babelrc I have:
```
{
    "presets": ["react-native"],
    "sourceMaps": true
}

```
I have also made use of `react-native-sm-transformer` 

## Expected Behavior
1. Breakpoints should be hit

## Software versions
- React-Native VS Code extension version: 
- VSCode version: 1.11.2
- OS platform and version: windows 10 Enterprise
- NodeJS version: v6.10.2
- React Native version: 0.43.3

## Outputs (Include if relevant)
- Output of the Debug Console (View -> Toggle Debug Console):
```
:app:packageDebug UP-TO-DATE
:app:assembleDebug UP-TO-DATE
:app:installDebug
Installing APK 'app-debug.apk' on 'Nexus7(AVD) - 7.0' for app:debug
Installed on 1 device.

BUILD SUCCESSFUL

Total time: 15.695 secs
Running C:\Users\eobey\AppData\Local\Android\android-sdk/platform-tools/adb -s emulator-5554 reverse tcp:8081 tcp:8081
adb server version (35) doesn't match this client (36); killing...
* daemon started successfully *
Starting the app on emulator-5554 (C:\Users\eobey\AppData\Local\Android\android-sdk/platform-tools/adb -s emulator-5554 shell am start -n com.wallet/.MainActivity)...
Starting: Intent { cmp=com.wallet/.MainActivity }
[vscode-react-native] Finished executing: react-native.cmd run-android
[vscode-react-native] Executing command: adb -s emulator-5554 shell am broadcast -a "com.wallet.RELOAD_APP_ACTION" --ez jsproxy true
[vscode-react-native] Broadcasting: Intent { act=com.wallet.RELOAD_APP_ACTION (has extras) }
Broadcast completed: result=0
[vscode-react-native] Finished executing: adb -s emulator-5554 shell am broadcast -a "com.wallet.RELOAD_APP_ACTION" --ez jsproxy true
[vscode-react-native] Starting debugger app worker.
[vscode-react-native] Established a connection with the Proxy (Packager) to the React Native application
[vscode-react-native] Debugger worker loaded runtime on port 42135
(node:12284) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
Running application "wallet" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF

```
- Output of the React-Native output channel (View -> Toggle Output -> Select React-Native in ListBox):
```
######### [Internal] [Info] Extension messaging server started at \\?\pipe\vscode-reactnative-679f39c503dc27b9ff694c72887914f8c9628e215d728c6466a855047f8bbcda. ##########
######### [Internal] [Info] Handling message: GET_PACKAGER_PORT ##########
######### [Internal] [Info] Handling message: SEND_TELEMETRY ##########
######### [Internal] [Info] Handling message: SEND_TELEMETRY ##########
######### [Internal] [Info] Handling message: START_PACKAGER ##########
Getting exponent dependecy.
######### Checking react native is correctly setup. This may take a while... ##########
Checking if the correct react native is installed..
######### Starting Packager ##########
######### Executing command: react-native.cmd start --port 8081 ##########
Scanning 563 folders for symlinks in c:\Development\wallet\node_modules (29ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running packager on port 8081.                                            │ 
 │                                                                            │ 
 │  Keep this packager running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own packager instance if you          │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   c:\Development\wallet 


React packager ready.

######### Packager started. ##########
######### [Internal] [Info] Handling message: SEND_TELEMETRY ##########
######### [Internal] [Info] Handling message: PREWARM_BUNDLE_CACHE ##########
######### [Internal] [Info] About to get: http://localhost:8081/index.android.bundle?platform=android ##########
Loading dependency graph, done.
Bundling `index.android.js`  100.0% (404/404), done.
######### The Bundle Cache was prewarmed. ##########
######### [Internal] [Info] Handling message: SEND_TELEMETRY ##########
Starting custom debugger by executing: echo A debugger is not needed:  "c:\Development\wallet"
######### [Internal] [Info] Handling message: START_MONITORING_LOGCAT ##########
######### [Internal] [Info] Handling message: SEND_TELEMETRY ##########
######### [Internal] [Info] Handling message: SEND_TELEMETRY ##########
######### [Internal] [Info] Handling message: SEND_TELEMETRY ##########
######### [Internal] [Info] Handling message: SEND_TELEMETRY ##########
Starting custom debugger by executing: echo A debugger is not needed:  "c:\Development\wallet"
Bundling `index.android.js`  100.0% (404/404), done.

```
- Output of the Developer Tools console (Help -> Toggle Developer Tools -> Select Console tab):
```
Overwriting extension <<.jsx>> to now point to mime <<text/x-jsx>>
2mime.ts:59Overwriting extension <<.jsx>> to now point to mime <<text/javascript>>
keybindingResolver.ts:129Conflict detected, command `workbench.action.debug.pause` cannot be triggered due to cordova.build
keybindingResolver.ts:129Conflict detected, command `workbench.action.debug.run` cannot be triggered due to cordova.run
```

### PR DESCRIPTION
**Pull request by vladimir-kotikov**
This PR enables typescript debugging + setting breakpoints in original typescript sources by implementing a logic to process react-native's bundle map and update source files mappings to point to original Typescript files.

This also works with any generated JS files that have source maps, not only with ones gennerated by Typescript. This also doesn't require to provide any special options to RN packager and hopefully would work with any future RN versions as it doesn't depend on any RN-specific features.

This resolves #441, resolves #328

### CODE REVIEW

**Comment by vladimir-kotikov** [comment]
@matrosov-nikita, could you please take a look?

**Comment by vladimir-kotikov** [comment]
This has been reviewed intenally, so merging. Thanks, @terbooter and @matrosov-nikita

**Comment by iShawnWang** [comment]
1. It seems that his was released in `React Native Tools v0.4.1' : Fixed bug in typescript sourcemaps rewrite logic when project and vscode are on different drives; 
2. but it seems not work, the VSCode still prompt something wrong with SourceMap and I have try to solve it by follow some github issues, still not work. 
3. where can I find some docs about how to config it properly ~ Thanks

# :D

**Comment by iTOYS** [comment]
Hello, @iShawnWang 
Could you open a new issue and fill it up with a template.
Thanks!

**Pull request merged**
