### PR TITLE
Add simulator device name to the setting

### PR DESCRIPTION
**Pull request by hnq90**
As I described in #462, I add a setting which let the user specify different simulator device than iPhone 6.

Please let me know if my PR needs changes.
Thanks in advance.

### CODE REVIEW

**Comment by hnq90** [comment]
@vladimir-kotikov Hi, should I close this PR?

**Comment by vladimir-kotikov** [comment]
@hnq90 thanks for your contribution and sorry for not responding earlier. I think you can keep it open if you don't mind - we'll evaluate it and may eventually merge as-is or with some changes.

As a side note - there is similar PR for Android platform https://github.com/Microsoft/vscode-react-native/pull/452 and looks like specifying particular device for running app on is in-demand feature. However we'd probably need to think over this a bit more to make behavior for different platforms consistent w/ other setting for specifying debug target (https://github.com/Microsoft/vscode-react-native/blob/master/package.json#L203-L206)

**Comment by hnq90** [comment]
@vladimir-kotikov It's good to hear that. I will keep it open for discussion but I think it's better to use `target`.

**Comment by vladimir-kotikov** [comment]
@hnq90, this PR has been integrated as a part of #512 with some additions. Thanks again for your contribution!

**Comment by hnq90** [comment]
@vladimir-kotikov Yes, thank you. I'm glad to hear that.

**Pull request closed without merging**
