### PR TITLE
make vscode-RN debug with TypeScript file

### PR DESCRIPTION
**Pull request by frogcjn**

### CODE REVIEW

**Comment by frogcjn** [comment]
@MSLaguana , here is the squashed branch

**Comment by MSLaguana** [comment]
Looks good, I'll merge it in now. Thanks a lot!

**Comment by joekim** [comment]
I'd love to started using the functionality. I've been waiting a while for a new release. Would it make sense to just grab this merge and start using it?

**Comment by MSLaguana** [comment]
We hope to publish a release in the near future, but if you want to use this now then you can check out master branch and build from that and it will include these changes.

**Comment by joewood** [comment]
Is this now released as part of 0.1.6?
TS Debugging still doesn't seem to work for me with this version. Is there an example project with this working? Any special settings for source maps required (e.g. inlineSourcemaps?)

**Comment by joewood** [comment]
OK, with a bit of experimenting I got this to work. I had to do a couple of things:
* I used `"inlineSourceMap":true` in the tsconfig.json.
* I made sure source maps were available for the root file (previously I had a JavaScript root JS file that simply required a separate TS file)

**Comment by tomauty** [comment]
@joewood can you post your tsconfig file? I can't seem to get this to work :(

**Pull request merged**
