### PR TITLE
Fix deprecated new Buffer() to Buffer.from

### LINKED ISSUE #1904: [Bug] 'new Buffer()' is deprecated due to security and usability issues
# 🐛 What is the bug? How can we reproduce it?

Please put here any steps, code or any information that can help us
reproduce the error on our side so we can fix it:

1. with the extension installed, access the Toggle Developer tools and check the console tab.

## Expected behavior

What were you expecting to happen?

I was hoping it would work normally, but a deprecated issue occurred in the extension host log in the console.
I dare to predict that VSC is down due to this.

## Debug output

<details>
<summary>Developer Tools console</summary>

```text

(node:9046) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper --trace-deprecation ...` to show where the warning was created)

```
</details>

## Environment

Please tell us about your system and your project:

* `envinfo`:

```text
  System:
    OS: macOS 11.2.3
    CPU: (8) arm64 Apple M1
    Memory: 520.13 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Watchman: 2021.12.13.00 - /opt/homebrew/bin/watchman
  Managers:
    Cargo: 1.63.0 - ~/.cargo/bin/cargo
    CocoaPods: 1.11.2 - /usr/local/bin/pod
    Homebrew: 3.3.8 - /opt/homebrew/bin/brew
    pip3: 21.3.1 - /opt/homebrew/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.30.1 - /usr/bin/git
    Clang: 12.0.5 - /usr/bin/clang
    FFmpeg: 4.4.1 - /opt/homebrew/bin/ffmpeg
  Servers:
    Apache: 2.4.46 - /usr/sbin/apachectl
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 30.0.2, 31.0.0
      System Images: android-31 | Google APIs ARM 64 v8a
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7678000
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_292 - /usr/bin/javac
    Perl: 5.28.2 - /usr/bin/perl
    PHP: 7.3.24 - /usr/bin/php
    Protoc: 3.17.3 - /opt/homebrew/bin/protoc
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.9.9 - /opt/homebrew/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
    Rust: 1.63.0 - /Users/jam/.cargo/bin/rustc
  Databases:
    MongoDB: 5.0.3 - /opt/homebrew/bin/mongo
    MySQL: 11.6 - /opt/homebrew/bin/mysql
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 109.0.5414.87
    Safari: 14.0.3
```

### PR DESCRIPTION
**Pull request by safethecode**
Fix #1904

### CODE REVIEW

**Comment by safethecode** [comment]
> 

@microsoft-github-policy-service agree [company="@safethecode"]

**Comment by safethecode** [comment]
> @safethecode please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement



> @safethecode please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by safethecode** [comment]
> @safethecode the command you issued was incorrect. Please try again.
> 
> Examples are:
> 
> ```
> @microsoft-github-policy-service agree
> ```
> 
> and
> 
> ```
> @microsoft-github-policy-service agree company="your company"
> ```

@microsoft-github-policy-service agree

**Review by EzioLi01 — APPROVED** [review]

**Comment by EzioLi01** [comment]
Thanks for the contribution!

**Pull request merged**
